WITH CUSTOMER_CONSECUTE_LOGINDATES
AS
    (
        SELECT
            CUSTOMER_ID,
            LOGIN_DATE,
            LAG(LOGIN_DATE) OVER(PARTITION BY CUSTOMER_ID ORDER BY LOGIN_DATE) AS LAST_LOGIN_DATE
        FROM {{source("raw","customer_login")}}
    )
SELECT
    *,
    DATEDIFF(DAY, LAST_LOGIN_DATE, LOGIN_DATE) AS CONSECUTIVE_DAYS
FROM CUSTOMER_CONSECUTE_LOGINDATES
QUALIFY DATEDIFF(DAY, LAST_LOGIN_DATE, LOGIN_DATE) > 2 AND DATEDIFF(DAY, LAST_LOGIN_DATE, LOGIN_DATE) IS NOT NULL